import { User, Role, Character, Attribute, Proficiency, Technique, TechniqueType, TechniqueLevel, Equipment } from './types';

export const initialUsers: User[] = [
    { id: 'master01', username: 'mestre', role: Role.MASTER, password: 'mestre01' },
    { id: 'player04', username: 'Jhuans', role: Role.PLAYER, password: 'resplandecido' },
    { id: 'player05', username: 'Ozy', role: Role.PLAYER, password: 'kamar' },
    { id: 'player06', username: 'coruja_gay', role: Role.PLAYER, password: 'pelorei' },
    { id: 'player07', username: 'gabriel', role: Role.PLAYER, password: 'sandman' },
];

export const ATTRIBUTE_LABELS: Record<Attribute, string> = {
    [Attribute.Corpo]: 'Corpo',
    [Attribute.Mente]: 'Mente',
    [Attribute.Espirito]: 'Espírito',
};

export const PROFICIENCY_LABELS: Record<Proficiency, string> = {
    [Proficiency.Resistencia]: 'Resistência',
    [Proficiency.DominioDeAura]: 'Domínio de Aura',
    [Proficiency.Marcialidade]: 'Marcialidade',
    [Proficiency.Investigacao]: 'Investigação',
    [Proficiency.Intimidacao]: 'Intimidação',
    [Proficiency.Reacao]: 'Reação',
    [Proficiency.Enganacao]: 'Enganação',
    [Proficiency.Conhecimento]: 'Conhecimento',
};

export const TECHNIQUE_TYPE_LABELS: Record<TechniqueType, string> = {
    [TechniqueType.Basica]: 'Básica',
    [TechniqueType.Avancada]: 'Avançada',
    [TechniqueType.Unica]: 'Única',
};

export const TECHNIQUE_LEVEL_LABELS: Record<TechniqueLevel, string> = {
    [TechniqueLevel.Amador]: 'Amador',
    [TechniqueLevel.Usuario]: 'Usuário',
    [TechniqueLevel.Experiente]: 'Experiente',
    [TechniqueLevel.Profissional]: 'Profissional',
    [TechniqueLevel.Graduado]: 'Graduado',
    [TechniqueLevel.Mestre]: 'Mestre',
    [TechniqueLevel.GraoMestre]: 'Grão-Mestre',
    [TechniqueLevel.Anciao]: 'Ancião',
};

export const PROFICIENCY_ATTRIBUTES: Record<Proficiency, Attribute[]> = {
    [Proficiency.Resistencia]: [Attribute.Corpo, Attribute.Mente, Attribute.Espirito],
    [Proficiency.DominioDeAura]: [Attribute.Espirito, Attribute.Mente],
    [Proficiency.Marcialidade]: [Attribute.Corpo, Attribute.Mente, Attribute.Espirito],
    [Proficiency.Investigacao]: [Attribute.Mente],
    [Proficiency.Intimidacao]: [Attribute.Corpo, Attribute.Espirito, Attribute.Mente],
    [Proficiency.Reacao]: [Attribute.Corpo, Attribute.Mente, Attribute.Espirito],
    [Proficiency.Enganacao]: [Attribute.Mente, Attribute.Espirito],
    [Proficiency.Conhecimento]: [Attribute.Mente, Attribute.Espirito],
};

export const ALL_PROFICIENCIES = Object.values(Proficiency);
export const ALL_ATTRIBUTES = Object.values(Attribute);
export const ALL_TECHNIQUE_LEVELS = Object.values(TechniqueLevel);

export const BASE_TECHNIQUES: Technique[] = [
    { name: 'Ten', description: 'Gasto: 80/turno. Efeito: defesa base de aura em volta do corpo (10 + Domínio de Aura + mod. de Mente + mod. de Espírito). Fica ativa por padrão e é suspensa em Zetsu.', type: TechniqueType.Basica, baseCost: 80, level: TechniqueLevel.Amador },
    { name: 'Zetsu', description: 'Gasto: 0. Efeito: suprime o fluxo externo de aura, oculta presença e alivia fadiga, mas remove as defesas naturais contra aura.', type: TechniqueType.Basica, baseCost: 0, level: TechniqueLevel.Amador },
    { name: 'Ren', description: 'Gasto: 100/turno (dobra após o 2º turno). Efeito: expande e intensifica aura, aumentando atributos em +2 e fortalecendo ataques/defesa.', type: TechniqueType.Basica, baseCost: 100, level: TechniqueLevel.Amador },
    { name: 'Ken', description: 'Gasto: 150/turno (dobra após o 2º turno). Efeito: defesa robusta de corpo inteiro com mitigação base 40 + Domínio de Aura + mods de Mente e Espírito.', type: TechniqueType.Avancada, baseCost: 150, level: TechniqueLevel.Amador },
    { name: 'In', description: 'Gasto: 300/uso. Efeito: oculta completamente aura em objeto/campo por até 100 turnos (1 dia), detectável por Gyo ou En.', type: TechniqueType.Avancada, baseCost: 300, level: TechniqueLevel.Amador },
    { name: 'Gyo', description: 'Gasto: 300 (ofensivo/defensivo), 150 (utilidade). Efeito: concentra aura em uma parte do corpo para amplificar ataque, defesa ou percepção.', type: TechniqueType.Avancada, baseCost: 300, level: TechniqueLevel.Amador },
    { name: 'Ko', description: 'Gasto: 400 (ofensivo/defensivo). Efeito: coagula quase toda aura em um único ponto para explosão extrema de impacto/proteção.', type: TechniqueType.Avancada, baseCost: 400, level: TechniqueLevel.Amador },
    { name: 'Shu', description: 'Gasto: 250 por objeto por cena/turno. Efeito: fortalece objeto com aura como extensão do corpo, aumentando dano e resistência.', type: TechniqueType.Avancada, baseCost: 250, level: TechniqueLevel.Amador },
    { name: 'En', description: 'Gasto: 200 a cada 5m de raio. Efeito: expande a aura em uma esfera para sentir presença, movimento e forma de alvos no alcance.', type: TechniqueType.Avancada, baseCost: 200, level: TechniqueLevel.Amador },
];

export const TECHNIQUE_LEVEL_MODIFIERS: Record<TechniqueLevel, { reductionBasic: number, reductionAdvanced: number, damageBonus: number, resistanceBonus: number, regenBonus: number }> = {
    [TechniqueLevel.Amador]: { reductionBasic: 1, reductionAdvanced: 1, damageBonus: 1, resistanceBonus: 1, regenBonus: 0 },
    [TechniqueLevel.Usuario]: { reductionBasic: 5, reductionAdvanced: 5, damageBonus: 1, resistanceBonus: 2, regenBonus: 0 },
    [TechniqueLevel.Experiente]: { reductionBasic: 8, reductionAdvanced: 8, damageBonus: 3, resistanceBonus: 3, regenBonus: 0 },
    [TechniqueLevel.Profissional]: { reductionBasic: 10, reductionAdvanced: 10, damageBonus: 4, resistanceBonus: 4, regenBonus: 0 },
    [TechniqueLevel.Graduado]: { reductionBasic: 15, reductionAdvanced: 15, damageBonus: 5, resistanceBonus: 5, regenBonus: 0 },
    [TechniqueLevel.Mestre]: { reductionBasic: 15, reductionAdvanced: 15, damageBonus: 10, resistanceBonus: 10, regenBonus: 0 },
    [TechniqueLevel.GraoMestre]: { reductionBasic: 20, reductionAdvanced: 20, damageBonus: 20, resistanceBonus: 20, regenBonus: 5 },
    [TechniqueLevel.Anciao]: { reductionBasic: 30, reductionAdvanced: 30, damageBonus: 30, resistanceBonus: 30, regenBonus: 15 },
};

export const PARADOX_EQUIPMENT: Equipment[] = [
    { id: 1, name: 'Arco', description: 'Uma arma de longo alcance que dispara projéteis de pura aura. Efeito: gastando 10 de aura, pode disparar 3 flechas adicionais.', buff: 'Os disparos podem ter efeito explosivo (+20 de dano em área por flecha) ou podem imobilizar os alvos.', debuff: 'Após 1 turno, perde 50 de aura e deve fazer um teste para não desmaiar.', imageUrl: 'https://picsum.photos/seed/newbow/200', question: 'Qual o princípio por trás da dualidade onda-partícula da luz?' },
    { id: 2, name: 'Bidente', description: 'Uma lança de duas pontas que canaliza a energia de combate. Efeito: golpes bem-sucedidos causam +10 de dano extra.', buff: 'Permite atacar 3 vezes em um único turno.', debuff: 'Enquanto empunha a arma, você rola um dado de desvantagem em todas as suas ações.', imageUrl: 'https://picsum.photos/seed/newbident/200', question: 'Explique a Terceira Lei de Newton.' },
    { id: 3, name: 'Glaive', description: 'Uma arma de haste pesada com uma lâmina mortal. Efeito: cada golpe bem-sucedido causa +20 de dano extra.', buff: 'Aumenta sua Força base em 10 pontos.', debuff: 'Após realizar um ataque, você perde seu próximo turno.', imageUrl: 'https://picsum.photos/seed/newglaive/200', question: 'O que é a constante de Planck e qual sua importância na mecânica quântica?' },
    { id: 4, name: 'Lâminas Gêmeas', description: 'Um par de adagas ágeis. Efeito: gastando 10 de aura, pode se teleportar para a localização de uma das lâminas e ganhar um ataque extra.', buff: 'Você ganha 2 ações extras neste turno.', debuff: 'Você precisa de 2 sucessos em 3 testes para conseguir realizar qualquer ação.', imageUrl: 'https://picsum.photos/seed/newblades/200', question: 'Descreva o conceito de entropia.' },
    { id: 5, name: 'Escudo Torre', description: 'Um escudo massivo que é quase uma muralha. Efeito: com uma ação, pode conjurar uma barreira protetora de 3 metros. Dano absorvido pela barreira aumenta permanentemente sua Vida ou Aura máxima.', buff: 'Todo dano que você causa ou recebe também restaura sua Vida e Aura atuais na mesma quantidade.', debuff: 'Todo dano que você receber é dobrado por 1 turno.', imageUrl: 'https://picsum.photos/seed/newshield/200', question: 'O que é o Princípio da Incerteza de Heisenberg?' },
    { id: 6, name: 'Chicote Elétrico', description: 'Um chicote flexível que estala com energia. Efeito: ataques bem-sucedidos drenam a mesma quantidade de dano da Vida e Aura do alvo.', buff: 'Todo o dano que você causa é dobrado.', debuff: 'Cada golpe desferido custa 50 de sua própria aura.', imageUrl: 'https://picsum.photos/seed/newwhip/200', question: 'Qual a diferença entre fissão e fusão nuclear?' },
    { id: 7, name: 'Armadura', description: 'Uma armadura completa que cobre todo o corpo. Efeito: aumenta todos os seus atributos em +10 e todas as suas perícias em +5 por 3 turnos.', buff: 'Todo dano absorvido pela armadura é armazenado. O dano guardado pode ser liberado como um feixe de energia concentrada.', debuff: 'Você não pode se mover por 2 turnos.', imageUrl: 'https://picsum.photos/seed/newarmor/200', question: 'Explique a Teoria da Relatividade Geral de Einstein.' },
    { id: 8, name: 'Martelo Pistolar', description: 'Um martelo de guerra com um mecanismo de disparo embutido. Efeito: sempre que causa dano, um disparo de energia causa o mesmo dano novamente e empurra o alvo 3 metros.', buff: 'Após causar duas instâncias de dano em um alvo, ele fica fragilizado, recebendo o dobro de dano do próximo golpe que o atingir.', debuff: 'Todos os ataques feitos contra você têm vantagem.', imageUrl: 'https://picsum.photos/seed/newhammer/200', question: 'O que são buracos negros e como se formam?' },
    { id: 9, name: 'Fuzil', description: 'Um fuzil de alta precisão. Efeito: pode disparar de 10 a 20 tiros por turno, cada um causando o dano base da arma.', buff: 'Você ganha um escudo de 100 de vida e fica invisível por 1 turno.', debuff: 'Seu corpo entra em estado de Zetsu total por 1 turno, deixando-o vulnerável.', imageUrl: 'https://picsum.photos/seed/newrifle/200', question: 'O que é matéria escura?' },
    { id: 10, name: 'Bose-Einstein', description: 'Um condensado de poder puro. Efeito: por 3 turnos, aumenta todos os seus atributos em +15 e perícias em +10. Você também ganha 1 turno extra e pode negar uma ação de um alvo.', buff: 'Você pode escolher manifestar qualquer outra arma da lista, já com o buff dela ativo, e ganha 1 ação extra.', debuff: 'Você desaparece da realidade por 1 rodada. Ao retornar, sua Vida e Aura atuais são cortadas pela metade e você fica atordoado por 1 turno.', imageUrl: 'https://picsum.photos/seed/newmagic/200', question: 'O que é o emaranhamento quântico?' },
];

const JHUAN_TECHNIQUES: Technique[] = [
    { name: 'Paradoxo do Conjurador', description: 'Custo: 200. Conjura uma de 10 armas com base em uma pergunta de física. Acertar concede um buff, errar um debuff. Não responder concede a arma neutra com dreno de aura e custo dobrado no próximo uso.', type: TechniqueType.Unica, baseCost: 200, level: TechniqueLevel.Amador },
    { name: 'Equação do Destino', description: 'Custo: 50. Inverte o resultado do Paradoxo. Um buff vira um debuff para o oponente e força seu próximo Paradoxo a ser um buff. Um debuff vira um buff para o oponente e força seu próximo Paradoxo a ser um debuff.', type: TechniqueType.Unica, baseCost: 50, level: TechniqueLevel.Amador },
];

const OZY_TECHNIQUES: Technique[] = [
    { name: 'Aura Expandir', description: 'Custo: 100 por conjuração. Técnica em 3 fases: mapeia área, enfraquece alvos intimidados e potencializa o usuário conforme quantidade de alvos afetados.', type: TechniqueType.Unica, baseCost: 100, level: TechniqueLevel.Amador },
    { name: 'Aura + Ego', description: 'Custo: 600 por turno. Executa Aura Expandir completa, ativa drenagem ampliada por alvo e permite converter drenagem em cura, aura atual, vida máxima ou aura máxima.', type: TechniqueType.Unica, baseCost: 600, level: TechniqueLevel.Amador },
];

const MATHEUS_TECHNIQUES: Technique[] = [
    { name: 'Prospecção Intuitiva', description: 'Custo: 500 por uso. Permite replicar habilidade, expor pontos fracos ou sugerir/controlar alvos com validação do Mestre.', type: TechniqueType.Unica, baseCost: 500, level: TechniqueLevel.Amador },
];

const GABRIEL_TECHNIQUES: Technique[] = [
    { name: 'Escudo do Mestre', description: 'Custo: 400 por uso. Possui 5 usos por dia e permite criar regras/efeitos com validação do Mestre.', type: TechniqueType.Unica, baseCost: 400, level: TechniqueLevel.Amador },
    { name: 'Regras da Casa', description: 'Custo: 100 por uso. Consome de 1 a 3 usos de Escudo do Mestre para criar regras válidas por 1 dia, com memória para reuso.', type: TechniqueType.Unica, baseCost: 100, level: TechniqueLevel.Amador },
    { name: 'Conjurar Taverna', description: 'Custo: 400 por uso. Conjura o Carvalho Ensandecido por 1 dia com opções de compras, missões e banco de moedas de aura.', type: TechniqueType.Unica, baseCost: 400, level: TechniqueLevel.Amador },
    { name: 'Ajustar Tokens da Party', description: 'Custo: 200 por uso. Move usuários conforme tipo de alvo e validação do Mestre.', type: TechniqueType.Unica, baseCost: 200, level: TechniqueLevel.Amador },
];

const createBaseTechniques = () => BASE_TECHNIQUES.map(tech => ({ ...tech, level: TechniqueLevel.Amador }));

const createOzyState = () => ({
    auraExpandir: {
        conjurationPhase: 0 as const,
        areaMeters: 0,
        alliesInArea: 0,
        enemiesInArea: 0,
        affectedCharacterIds: [] as string[],
        intimidationThreshold: 0,
        intimidatedTargets: 0,
        resistancePenaltyApplied: 0,
        isActive: false,
    },
    egoTargetsInRange: 0,
    passiveEgoEnabled: true,
    auraPlusEgoActive: false,
    auraPlusEgoConversion: 'heal_aura' as const,
});

const createMatheusState = () => ({
    isChoosingProspectionAction: false,
    pendingRequest: null,
    lastResolvedRequest: null,
    copiedTechniques: [],
});

const createGabrielState = () => ({
    escudoDoMestreUsesRemaining: 5,
    armedEscudoDoMestre: false,
    armedRegrasDaCasa: false,
    armedAjustarTokens: false,
    pendingEscudoRequest: null,
    pendingHouseRuleRequest: null,
    storedHouseRules: [],
    activeHouseRuleId: null,
    activeHouseRuleUntilDay: null,
    pendingTokenAdjustRequest: null,
    tavern: {
        isActive: false,
        activeUntilDay: null,
        bankAuraCoins: 0,
        infoPrice: 0,
        foodPrice: 0,
        lodgingPrice: 0,
        items: [],
        missions: [],
    },
    dailyInteractionsUsed: 0,
});

export const initialCharacters: Character[] = [
    {
        id: 'char04',
        name: 'Jhuan K.',
        playerId: 'player04',
        imageUrl: 'https://picsum.photos/seed/jhuan/400/600',
        age: '28',
        backstory: 'Um físico teórico que descobriu a existência da aura através de seus estudos sobre anomalias quânticas. Sua habilidade de Nen é uma manifestação direta de sua compreensão das leis do universo, permitindo-lhe dobrar a realidade de maneiras sutis, mas poderosas.',
        motivations: 'Provar que a ciência e o Nen são duas faces da mesma moeda.',
        inventory: 'Caderno de anotações, caneta de ponta fina, um pequeno dodecaedro de metal.',
        wealth: 1500,
        attributes: { [Attribute.Mente]: 16, [Attribute.Corpo]: 6, [Attribute.Espirito]: 3 },
        proficiencies: {
            [Proficiency.Resistencia]: 2,
            [Proficiency.DominioDeAura]: 5,
            [Proficiency.Marcialidade]: 5,
            [Proficiency.Investigacao]: 2,
            [Proficiency.Intimidacao]: 1,
            [Proficiency.Reacao]: 2,
            [Proficiency.Enganacao]: 0,
            [Proficiency.Conhecimento]: 8,
        },
        currentAura: 54,
        currentHealth: -1,
        tempHealth: 0,
        barriers: 0,
        techniques: [...createBaseTechniques(), ...JHUAN_TECHNIQUES.map(t => ({ ...t, level: TechniqueLevel.Amador }))],
        effects: [],
        testRequest: null,
        combatLog: ['Sessão iniciada.'],
        unspentAttributePoints: 0,
        unspentProficiencyPoints: 0,
        paradoxState: { isActive: false, question: '', playerAnswer: null, nextUseCostDoubled: false, isEquationOfDestinyActive: false, forceNextBuff: false, forceNextDebuff: false, activeNeutralWeapon: false, selectedEquipment: null, preparedExtraShots: 0 },
        actions: { attacks: 1, totalAttacks: 1 },
        pendingAttack: null,
        maxAuraPermanentBonus: 0,
        maxHealthPermanentBonus: 0,
        absorbedDamageForConversion: 0,
        tavernDailyInteractionsUsed: 0,
        tavernUsedOptions: [],
        tavernLastInteractionRound: -1,
        pendingTavernSellRequest: null,
        activeTavernMissionId: null,
    },
    {
        id: 'char05',
        name: 'Ozymandias',
        playerId: 'player05',
        imageUrl: 'https://picsum.photos/seed/ozy/400/600',
        age: '',
        backstory: '',
        motivations: '',
        inventory: '',
        wealth: 0,
        attributes: { [Attribute.Mente]: 9, [Attribute.Corpo]: 8, [Attribute.Espirito]: 19 },
        proficiencies: {
            [Proficiency.Resistencia]: 5,
            [Proficiency.DominioDeAura]: 10,
            [Proficiency.Marcialidade]: 5,
            [Proficiency.Investigacao]: 0,
            [Proficiency.Intimidacao]: 5,
            [Proficiency.Reacao]: 5,
            [Proficiency.Enganacao]: 0,
            [Proficiency.Conhecimento]: 0,
        },
        currentAura: 1368,
        currentHealth: 32,
        tempHealth: 0,
        barriers: 0,
        techniques: [...createBaseTechniques(), ...OZY_TECHNIQUES.map(t => ({ ...t, level: TechniqueLevel.Amador }))],
        effects: [],
        testRequest: null,
        combatLog: ['Sessão iniciada.'],
        unspentAttributePoints: 0,
        unspentProficiencyPoints: 0,
        actions: { attacks: 1, totalAttacks: 1 },
        pendingAttack: null,
        maxAuraPermanentBonus: 0,
        maxHealthPermanentBonus: 0,
        absorbedDamageForConversion: 0,
        ozyState: createOzyState(),
        tavernDailyInteractionsUsed: 0,
        tavernUsedOptions: [],
        tavernLastInteractionRound: -1,
        pendingTavernSellRequest: null,
        activeTavernMissionId: null,
    },
    {
        id: 'char06',
        name: 'Matheus',
        playerId: 'player06',
        imageUrl: 'https://picsum.photos/seed/matheus/400/600',
        age: '',
        backstory: '',
        motivations: '',
        inventory: '',
        wealth: 0,
        attributes: { [Attribute.Mente]: 20, [Attribute.Corpo]: 8, [Attribute.Espirito]: 15 },
        proficiencies: {
            [Proficiency.Resistencia]: 3,
            [Proficiency.DominioDeAura]: 6,
            [Proficiency.Marcialidade]: 3,
            [Proficiency.Investigacao]: 2,
            [Proficiency.Intimidacao]: 0,
            [Proficiency.Reacao]: 3,
            [Proficiency.Enganacao]: 4,
            [Proficiency.Conhecimento]: 4,
        },
        currentAura: 2400,
        currentHealth: 56,
        tempHealth: 0,
        barriers: 0,
        techniques: [...createBaseTechniques(), ...MATHEUS_TECHNIQUES.map(t => ({ ...t, level: TechniqueLevel.Amador }))],
        effects: [],
        testRequest: null,
        combatLog: ['Sessão iniciada.'],
        unspentAttributePoints: 0,
        unspentProficiencyPoints: 0,
        actions: { attacks: 1, totalAttacks: 1 },
        pendingAttack: null,
        maxAuraPermanentBonus: 0,
        maxHealthPermanentBonus: 0,
        absorbedDamageForConversion: 0,
        matheusState: createMatheusState(),
        tavernDailyInteractionsUsed: 0,
        tavernUsedOptions: [],
        tavernLastInteractionRound: -1,
        pendingTavernSellRequest: null,
        activeTavernMissionId: null,
    },
    {
        id: 'char07',
        name: 'Gabriel',
        playerId: 'player07',
        imageUrl: 'https://picsum.photos/seed/gabriel/400/600',
        age: '',
        backstory: '',
        motivations: '',
        inventory: '',
        wealth: 0,
        attributes: { [Attribute.Mente]: 19, [Attribute.Corpo]: 12, [Attribute.Espirito]: 19 },
        proficiencies: {
            [Proficiency.Resistencia]: 3,
            [Proficiency.DominioDeAura]: 10,
            [Proficiency.Marcialidade]: 0,
            [Proficiency.Investigacao]: 5,
            [Proficiency.Intimidacao]: 0,
            [Proficiency.Reacao]: 2,
            [Proficiency.Enganacao]: 0,
            [Proficiency.Conhecimento]: 7,
        },
        currentAura: 4332,
        currentHealth: 108,
        tempHealth: 0,
        barriers: 0,
        techniques: [...createBaseTechniques(), ...GABRIEL_TECHNIQUES.map(t => ({ ...t, level: TechniqueLevel.Amador }))],
        effects: [],
        testRequest: null,
        combatLog: ['Sessão iniciada.'],
        unspentAttributePoints: 0,
        unspentProficiencyPoints: 0,
        actions: { attacks: 1, totalAttacks: 1 },
        pendingAttack: null,
        maxAuraPermanentBonus: 0,
        maxHealthPermanentBonus: 0,
        absorbedDamageForConversion: 0,
        gabrielState: createGabrielState(),
        tavernDailyInteractionsUsed: 0,
        tavernUsedOptions: [],
        tavernLastInteractionRound: -1,
        pendingTavernSellRequest: null,
        activeTavernMissionId: null,
    },
];

export const createNewCharacter = (playerId: string, name: string): Character => ({
    id: `char_${playerId}`,
    name,
    playerId,
    imageUrl: `https://picsum.photos/seed/${name.toLowerCase()}/400/600`,
    age: '',
    backstory: '',
    motivations: '',
    inventory: '',
    wealth: 0,
    attributes: { [Attribute.Corpo]: 10, [Attribute.Mente]: 10, [Attribute.Espirito]: 10 },
    proficiencies: {
        [Proficiency.Resistencia]: 0,
        [Proficiency.DominioDeAura]: 0,
        [Proficiency.Marcialidade]: 0,
        [Proficiency.Investigacao]: 0,
        [Proficiency.Intimidacao]: 0,
        [Proficiency.Reacao]: 0,
        [Proficiency.Enganacao]: 0,
        [Proficiency.Conhecimento]: 0,
    },
    currentAura: 110,
    currentHealth: 10,
    tempHealth: 0,
    barriers: 0,
    techniques: createBaseTechniques(),
    effects: [],
    testRequest: null,
    combatLog: ['Personagem criado.'],
    unspentAttributePoints: 0,
    unspentProficiencyPoints: 0,
    actions: { attacks: 1, totalAttacks: 1 },
    pendingAttack: null,
    maxAuraPermanentBonus: 0,
    maxHealthPermanentBonus: 0,
    absorbedDamageForConversion: 0,
    tavernDailyInteractionsUsed: 0,
    tavernUsedOptions: [],
    tavernLastInteractionRound: -1,
    pendingTavernSellRequest: null,
    activeTavernMissionId: null,
});
